services:
  backend:
    build:
      context: ./backend
    image: backend
    ports:
      - "8000:8000"
    volumes:
      - share-data:/backend/best_performance
    tty: true
    stdin_open: true

  frontend_test:
    build: ./frontend
    image: frontend_test
    command: ["npm", "run", "test"]
    depends_on:
      - backend

  frontend:
    build:
      context: ./frontend
    image: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - frontend_test


volumes:
  share-data:
